### ISSUE TITLE
Error: accountSid must start with AC

### ISSUE THREAD

**Issue by jme2712** [jef/streetmerchant#1004]
When attempting to setup Docker I get the subject error and the below.

Error: accountSid must start with AC
    at new Twilio (/app/node_modules/twilio/lib/rest/Twilio.js:140:11)
    at Object.<anonymous> (/app/build/notification/twilio.js:10:14)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/app/build/notification/notification.js:17:18)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! streetmerchant@ start:production: `node build/index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the streetmerchant@ start:production script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by BaileyMillerSSI** [comment]
Did you solve this?

**Comment by jme2712** [comment]
That part yes just by removing from the env confit. However if I have my email an phone setup in env will i get notifications when Stock drops?

**Comment by BaileyMillerSSI** [comment]
I fixed this by switching to the nightly build for docker and the latest version for the git branch. Also removing settings from the .env that were empty.
