### ISSUE TITLE
error :: ✖ something bad happened, resetting streetmerchant in 5 seconds Failed to launch the browser process!

### ISSUE THREAD

**Issue by AlphaOmega2020** [jef/streetmerchant#1072]
### Description

error when launching following an out of the box pull, using the docker compose below + .env:
```
streetmerchant    |
streetmerchant    | > streetmerchant@ start:production /app
streetmerchant    | > node build/index.js
streetmerchant    |
streetmerchant    | ＳＴＲＥＥＴＭＥＲＣＨＡＮＴ
streetmerchant    | 3.1.0
streetmerchant    |
streetmerchant    | [7:21:51 PM] warn :: nvidia is deprecated in favor of bestbuy
streetmerchant    | [7:21:51 PM] info :: ℹ selected stores: nvidia
streetmerchant    | [7:21:51 PM] info :: ℹ selected series: 3070, 3080, 3090, rx6800, rx6800xt, rx6900xt, ryzen5600, ryzen5800, ryzen5900, ryzen5950, sonyps5c, sonyps5de, xboxss, xboxsx
streetmerchant    | [7:21:52 PM] error :: ✖ something bad happened, resetting streetmerchant in 5 seconds Failed to launch the browser process!
streetmerchant    | Failed to move to new namespace: PID namespaces supported, Network namespace supported, but failed: errno = Operation not permitted
streetmerchant    | [1201/192152.876695:FATAL:zygote_host_impl_linux.cc(191)] Check failed: ReceiveFixedMessage(fds[0], kZygoteBootMessage, sizeof(kZygoteBootMessage), &boot_pid).
streetmerchant    | Received signal 6
streetmerchant    |   r8: 00007ffd3e08c894  r9: 00005615f4e60ec0 r10: 0000000000000008 r11: 0000000000000246
streetmerchant    |  r12: 00007ffd3e08ced0 r13: 00007ffd3e08ce0c r14: 00005615f4e60af0 r15: 00000000000000a0
streetmerchant    |   di: 0000000000000002  si: 00007ffd3e08c760  bp: 00007ffd3e08c760  bx: 0000000000000000
streetmerchant    |   dx: 0000000000000000  ax: 0000000000000000  cx: 00007fe5af6fca71  sp: 00007ffd3e08c758
streetmerchant    |   ip: 00007fe5af6fca71 efl: 0000000000000246 cgf: aaaa000000000033 erf: 0000000000000000
streetmerchant    |  trp: 0000000000000000 msk: 0000000000000000 cr2: 0000000000000000
streetmerchant    | [end of stack trace]
streetmerchant    | Calling _exit(1). Core file will not be generated.
streetmerchant    |
streetmerchant    |
streetmerchant    | TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md
streetmerchant    |  {
streetmerchant    |   "stack": "Error: Failed to launch the browser process!\nFailed to move to new namespace: PID namespaces supported, Network namespace supported, but failed: errno = Operation not permitted\n[1201/192152.876695:FATAL:zygote_host_impl_linux.cc(191)] Check failed: ReceiveFixedMessage(fds[0], kZygoteBootMessage, sizeof(kZygoteBootMessage), &boot_pid). \nReceived signal 6\n  r8: 00007ffd3e08c894  r9: 00005615f4e60ec0 r10: 0000000000000008 r11: 0000000000000246\n r12: 00007ffd3e08ced0 r13: 00007ffd3e08ce0c r14: 00005615f4e60af0 r15: 00000000000000a0\n  di: 0000000000000002  si: 00007ffd3e08c760  bp: 00007ffd3e08c760  bx: 0000000000000000\n  dx: 0000000000000000  ax: 0000000000000000  cx: 00007fe5af6fca71  sp: 00007ffd3e08c758\n  ip: 00007fe5af6fca71 efl: 0000000000000246 cgf: aaaa000000000033 erf: 0000000000000000\n trp: 0000000000000000 msk: 0000000000000000 cr2: 0000000000000000\n[end of stack trace]\nCalling _exit(1). Core file will not be generated.\n\n\nTROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md\n\n    at onClose (/app/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:193:20)\n    at ChildProcess.<anonymous> (/app/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:184:79)\n    at ChildProcess.emit (events.js:327:22)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)"

```

compose:
```
streetmerchant:
        container_name: streetmerchant
        environment:
            - 'PUID=1000'
            - 'PGID=100'
            - 'TZ=Europe/London'
            - 'PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser'
            - 'PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=1'
        network_mode: default
        volumes:
            - '/share/Container/container-station-data/appdata/streetmerchant/config/.env:/.env'
        restart: unless-stopped
        image: ghcr.io/jef/streetmerchant:latest
```

.env

```
# ** All configuration variables are optional **
# Read https://github.com/jef/streetmerchant#customization for help on customizing this file
#############################################################################################

COUNTRY=UK
HEADLESS=true
IN_STOCK_WAIT_TIME=1
LOW_BANDWIDTH=true
MAX_PRICE_SERIES_3070=1
MAX_PRICE_SERIES_3080=1
MAX_PRICE_SERIES_3090=1000
MAX_PRICE_SERIES_RX6800=1
MAX_PRICE_SERIES_RX6800XT=650
MAX_PRICE_SERIES_RX6900XT=800
MAX_PRICE_SERIES_RYZEN5600=1
MAX_PRICE_SERIES_RYZEN5800=1
MAX_PRICE_SERIES_RYZEN5900=1
MAX_PRICE_SERIES_RYZEN5950=751
PLAY_SOUND=Heartbeat-sound-effect.mp3
STORES=scan,amazon-uk,amd,box,currys,game,novatech,overclockers,very
```

Docker Version
```
[~] # docker version
Client:
 Version:      17.09.1-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   0bbe3ac
 Built:        Wed Nov 27 03:52:27 2019
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.1-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   0bbe3ac
 Built:        Wed Nov 27 03:52:27 2019
 OS/Arch:      linux/amd64
 Experimental: false
```

**Comment by AlphaOmega2020** [comment]
resolved by adding the following to the compose file

```
        cap_add:
            - 'SYS_ADMIN'
        env_file:
            - '/share/Container/container-station-data/appdata/streetmerchant/config/.env'
```
