### ISSUE TITLE
Unable to send discord notifications

### ISSUE THREAD

**Issue by scurker** [jef/streetmerchant#1254]
## Expected Behavior

A discord notification is created

## Current Behavior

An error prevents discord notifications from being created

> couldn't send discord message fields.flat is not a function

## Steps to Reproduce

1. Using the below `.env` file with `npm run test:notification`

## Environment

**OS:**

MacOS Catalina 10.15.7

**.env file:**

```dotenv
DISCORD_WEB_HOOK=https://discordapp.com/api/webhooks/[webhookid]
```

## Logs

```json
{
  "stack": "TypeError: fields.flat is not a function
    at Function.normalizeFields (/Users/jwilson/projects/streetmerchant/node_modules/discord.js/src/structures/MessageEmbed.js:450:8)
    at MessageEmbed.addFields (/Users/jwilson/projects/streetmerchant/node_modules/discord.js/src/structures/MessageEmbed.js:266:42)
    at MessageEmbed.addField (/Users/jwilson/projects/streetmerchant/node_modules/discord.js/src/structures/MessageEmbed.js:257:17)
    at /Users/jwilson/projects/streetmerchant/build/notification/discord.js:33:23
    at Object.sendDiscordMessage (/Users/jwilson/projects/streetmerchant/build/notification/discord.js:60:11)
    at Object.sendNotification (/Users/jwilson/projects/streetmerchant/build/notification/notification.js:27:15)
    at Object.<anonymous> (/Users/jwilson/projects/streetmerchant/build/__test__/notification-test.js:25:16)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)"
}
```

**Comment by scurker** [comment]
It looks like https://github.com/jef/streetmerchant/issues/1188 was recently merged, which swapped out the discord libraries. Notifications were working for me prior to this change.

**Comment by jef** [comment]
Unfortunately I can't duplicate.

![image](https://user-images.githubusercontent.com/12074633/101513373-1786b780-394a-11eb-8d27-1c4944696c61.png)

Please run `npm install`.

**Comment by scurker** [comment]
I found the root of the issue. `Array.flat` is not available until Node 11, and I'm currently using `v10.15.3`.

**Comment by jef** [comment]
We run builds on 14.15.0 for future reference!

Thanks and good luck!
