### ISSUE TITLE
Error: Request Interception is not enabled

### ISSUE THREAD

**Issue by nazmi** [jef/streetmerchant#1264]
## Current Behavior
Throws error only when i change PAGE_BACKOFF_MIN values

## Steps to Reproduce

1. Set store to 503/else
2. PAGE_BACKOFF_MIN="60000"

## Environment

**OS:** Windows 10 20H2
**.env file:**

```dotenv
PAGE_BACKOFF_MIN="60000"
SHOW_ONLY_SERIES="ryzen5600"
STORES="ccl"

```

## Logs
[6:43:26 pm] warn :: ✖ [ccl] [amd (ryzen5600)] 5600x :: STATUS CODE ERROR 503
[6:44:36 pm] info :: [ccl] Running linksBuilder...
[6:44:36 pm] warn :: ✖ [ccl] [amd (ryzen5600)] 5600x :: STATUS CODE ERROR 503
(node:15808) UnhandledPromiseRejectionWarning: Error: Request Interception is not enabled!
    at Object.exports.assert (C:\streetmerchant\node_modules\puppeteer\lib\cjs\puppeteer\common\assert.js:26:15)
    at Proxy.respond (C:\streetmerchant\node_modules\puppeteer\lib\cjs\puppeteer\common\HTTPRequest.js:270:21)
    at PuppeteerBlocker.onRequest (C:\streetmerchant\node_modules\@cliqz\adblocker-puppeteer\adblocker.ts:301:17)
    at BlockingContext.onRequest (C:\streetmerchant\node_modules\@cliqz\adblocker-puppeteer\adblocker.ts:62:43)
    at C:\streetmerchant\src\store\lookup.ts:111:3
    at new Promise (<anonymous>)
    at handleAdBlock (C:\streetmerchant\src\store\lookup.ts:85:9)
    at C:\streetmerchant\src\store\lookup.ts:197:14
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:15808) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 173)
(node:15808) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[6:46:45 pm] info :: [ccl] Running linksBuilder...
[6:46:50 pm] warn :: ✖ [ccl] [amd (ryzen5600)] 5600x :: STATUS CODE ERROR 503

**Comment by jef** [comment]
Duplicate

https://github.com/cliqz-oss/adblocker/issues/1495
https://github.com/jef/streetmerchant/issues/826
