### ISSUE TITLE
Cannot find module 'random-useragent' or its corresponding type declarations.

### ISSUE THREAD

**Issue by isma373** [jef/streetmerchant#1365]
## Steps to Reproduce

1.
2.
3.
4.

## Environment

**OS:**
**dotenv file:**

```dotenv

```

**Comment by isma373** [comment]
I am getting the following: 

`TSError: ⨯ Unable to compile TypeScript:
src/util.ts(5,25): error TS2307: Cannot find module 'random-useragent' or its corresponding type declarations.
src/util.ts(97,14): error TS7006: Parameter 'ua' implicitly has an 'any' type.

    at createTSError (C:\Users\user\streetmerchant\node_modules\ts-node\src\index.ts:513:12)
    at reportTSError (C:\Users\user\streetmerchant\node_modules\ts-node\src\index.ts:517:19)
    at getOutput (C:\Users\user\streetmerchant\node_modules\ts-node\src\index.ts:752:36)
    at Object.compile (C:\Users\user\streetmerchant\node_modules\ts-node\src\index.ts:968:32)
    at Module.m._compile (C:\Users\user\streetmerchant\node_modules\ts-node\src\index.ts:1056:42)
    at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.require.extensions.<computed> [as .ts] (C:\Users\user\streetmerchant\node_modules\ts-node\src\index.ts:1059:12)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
`

**Comment by sohaiiil** [comment]
You need to run `npm i` to install the new dependency

**Comment by isma373** [comment]
> You need to run `npm i` to install the new dependency

Sorry, I am stupid :) Fixed.
