### ISSUE TITLE
StreetMerchant crashes on launch.

### ISSUE THREAD

**Issue by the-garbage-which-belongs-to-waffle** [jef/streetmerchant#1536]
## Expected Behavior

The app should launch.

## Current Behavior

It errors.

## Environment

**OS:** Raspberry Pi OS.
**dotenv file:**

```# ** All configuration variables are optional **
# Copy this file and name it as `dotenv` (without backticks)
# Read https://jef.codes/streetmerchant/getting-started/#customization for help on customizing this file
########################################################################################################

AUTO_ADD_TO_CART="false"
COUNTRY="great_britain"
DISCORD_NOTIFY_GROUP="<@302130625568309260>"
DISCORD_NOTIFY_GROUP_3060TI="<@302130625568309260>"
DISCORD_NOTIFY_GROUP_3070="<@302130625568309260>"
DISCORD_WEB_HOOK="https://discord.com/api/webhooks/[redacted]
IN_STOCK_WAIT_TIME="1"
MAX_PRICE_SERIES_3060TI="1000"
MAX_PRICE_SERIES_3070="1000"
MAX_PRICE_SERIES_3080="1"
MAX_PRICE_SERIES_3090="1"
MAX_PRICE_SERIES_CORSAIR_SF="1"
MAX_PRICE_SERIES_RX6800="1"
MAX_PRICE_SERIES_RX6800XT="1"
MAX_PRICE_SERIES_RX6900XT="1"
MAX_PRICE_SERIES_RYZEN5600="1"
MAX_PRICE_SERIES_RYZEN5800="1"
MAX_PRICE_SERIES_RYZEN5900="1"
MAX_PRICE_SERIES_RYZEN5950="1"
MAX_PRICE_SERIES_SONYPS5C="1"
MAX_PRICE_SERIES_SONYPS5DE="1"
MAX_PRICE_SERIES_XBOXSS="1"
MAX_PRICE_SERIES_XBOXSX="1"
MAX_PRICE_SERIES_TEST="1"
PAGE_SLEEP_MIN="30000"
PAGE_SLEEP_MAX="35000"
SCREENSHOT="false"
STORES="amazon-uk,amd-uk,argos,aria,awd,box,ccl,currys,ebuyer,johnlewis,novatech,overclockers,scan,shopto,very"

```

## Logs

`TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md
 {
  "stack": "Error: Failed to launch the browser process!\n/home/pi/streetmerchant/node_modules/puppeteer/.local-chromium/linux-818858/chrome-linux/chrome: 1: /home/pi/streetmerchant/node_modules/puppeteer/.local-chromium/linux-818858/chrome-linux/chrome: Syntax error: \"(\" unexpected\n\n\nTROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md\n\n    at onClose (/home/pi/streetmerchant/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:193:20)\n    at Interface.<anonymous> (/home/pi/streetmerchant/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:183:68)\n    at Interface.emit (events.js:327:22)\n    at Interface.close (readline.js:424:8)\n    at Socket.onend (readline.js:202:10)\n    at Socket.emit (events.js:327:22)\n    at endReadableNT (internal/streams/readable.js:1327:12)\n    at processTicksAndRejections (internal/process/task_queues.js:80:21)"
}
[16:39:06] error :: ��� something bad happened, resetting streetmerchant in 5 seconds Failed to launch the browser process!
/home/pi/streetmerchant/node_modules/puppeteer/.local-chromium/linux-818858/chrome-linux/chrome: 1: /home/pi/streetmerchant/node_modules/puppeteer/.local-chromium/linux-818858/chrome-linux/chrome: Syntax error: "(" unexpected`

**Comment by the-garbage-which-belongs-to-waffle** [comment]
Note: I have tried running with the options on the wiki, but it freezes.

**Comment by the-garbage-which-belongs-to-waffle** [comment]
Fixed by installing the Debian libraries.
