### ISSUE TITLE
Error: Cannot find module 'cheerio-select-tmp' ubuntu 20.04

### ISSUE THREAD

**Issue by nmolanog** [jef/streetmerchant#2397]
## Expected Behavior

npm run start running

## Current Behavior

after running npm install I get the following:
`npm WARN EBADENGINE Unsupported engine { package: 'streetmerchant@3.5.0',
npm WARN EBADENGINE   required: { node: '>=12.0.0' },
npm WARN EBADENGINE   current: { node: 'v10.19.0', npm: '7.6.0' } }
npm WARN EBADENGINE Unsupported engine { package: '@slack/web-api@6.1.0',
npm WARN EBADENGINE   required: { node: '>= 12.13.0', npm: '>= 6.12.0' },
npm WARN EBADENGINE   current: { node: 'v10.19.0', npm: '7.6.0' } }
npm WARN EBADENGINE Unsupported engine { package: 'discord.js@12.5.3',
npm WARN EBADENGINE   required: { node: '>=12.0.0' },
npm WARN EBADENGINE   current: { node: 'v10.19.0', npm: '7.6.0' } }
npm WARN EBADENGINE Unsupported engine { package: 'open@8.0.5',
npm WARN EBADENGINE   required: { node: '>=12' },
npm WARN EBADENGINE   current: { node: 'v10.19.0', npm: '7.6.0' } }

removed 4 packages, and audited 1183 packages in 3s

29 packages are looking for funding
  run `npm fund` for details

2 high severity vulnerabilities

Some issues need review, and may require choosing
a different dependency.`

running npm audit gets:

`# npm audit report

axios  <0.21.1
Severity: high
Server-Side Request Forgery - https://npmjs.com/advisories/1594
No fix available
node_modules/@bridgerakol/samsung-smart-api/node_modules/axios
  @bridgerakol/samsung-smart-api  *
  Depends on vulnerable versions of axios
  node_modules/@bridgerakol/samsung-smart-api

2 high severity vulnerabilities

Some issues need review, and may require choosing
a different dependency.`

running npm run start gets:

`10:18:13 AM] warn :: ℹ some of the selected stores (grayed out) dont have what you are looking for
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'cheerio-select-tmp'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/nicolas/streetmerchant/node_modules/cheerio/lib/static.js:11:14)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)`

## Steps to Reproduce

see above

## Environment

- OS: ubuntu 20.04

I apreciate any help to solve this issue

**Comment by nmolanog** [comment]
Had to do a clean install of nodejs and npm to fix this. sorry for the inconvenience
