### ISSUE TITLE
[Bug]: puppeteer Failed to launch the browser process!

### ISSUE THREAD

**Issue by Speedmod88** [jef/streetmerchant#2747]
### Expected Behavior

After updating to the new version I got this

[10 h 23 min 53 s] error :: ✖ something bad happened, resetting streetmerchant in 5 seconds Failed to launch the browser process!

TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md
 {
  "stack": "Error: Failed to launch the browser process!\n\n\nTROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md\n\n    at onClose (C:\\Users\\FTW\\streetmerchant\\node_modules\\puppeteer\\lib\\cjs\\puppeteer\\node\\BrowserRunner.js:194:20)\n    at Interface.<anonymous> (C:\\Users\\FTW\\streetmerchant\\node_modules\\puppeteer\\lib\\cjs\\puppeteer\\node\\BrowserRunner.js:184:68)\n    at Interface.emit (node:events:406:35)\n    at Interface.close (node:readline:586:8)\n    at Socket.onend (node:readline:277:10)\n    at Socket.emit (node:events:406:35)\n    at endReadableNT (node:internal/streams/readable:1343:12)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)"
}

### Current Behavior

I updated Node to newer version v16.8.0
streetmerchant 3.5.0

I tried also node node_modules/puppeteer/install.js

### What operating system are you seeing the problem on?

Windows

### Relevant log output

```shell
npm run start

> streetmerchant@3.5.0 prestart
> npm run compile


> streetmerchant@3.5.0 compile
> tsc


> streetmerchant@3.5.0 start
> node build/src/index.js

ＳＴＲＥＥＴＭＥＲＣＨＡＮＴ
3.5.0
[10 h 29 min 57 s] info :: ℹ selected series: sonyps5c, rx6800xt, rx6900xt, 3080, 3090, 3060ti
[10 h 29 min 57 s] info :: ℹ selected stores: amazon-ca, amd-ca, bestbuy-ca, canadacomputers, ebgames, memoryexpress, newegg-ca, walmart-ca, vuugo
[10 h 29 min 59 s] error :: ✖ something bad happened, resetting streetmerchant in 5 seconds Failed to launch the browser process!


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md
 {
  "stack": "Error: Failed to launch the browser process!\n\n\nTROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md\n\n    at onClose (C:\\Users\\FTW\\streetmerchant\\node_modules\\puppeteer\\lib\\cjs\\puppeteer\\node\\BrowserRunner.js:194:20)\n    at Interface.<anonymous> (C:\\Users\\FTW\\streetmerchant\\node_modules\\puppeteer\\lib\\cjs\\puppeteer\\node\\BrowserRunner.js:184:68)\n    at Interface.emit (node:events:406:35)\n    at Interface.close (node:readline:586:8)\n    at Socket.onend (node:readline:277:10)\n    at Socket.emit (node:events:406:35)\n    at endReadableNT (node:internal/streams/readable:1343:12)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)"
}
```

### Configuration

```shell
# ** All configuration variables are optional **
# Copy this file and name it as `dotenv` (without backticks)
# Read https://jef.codes/streetmerchant/getting-started/#customization for help on customizing this file
########################################################################################################

ASCII_BANNER=
ASCII_COLOR=
APNS_AUTHKEY=
APNS_BUNDLEID=
APNS_DEVICETOKEN=
APNS_KEYID=
APNS_PRODUCTION=
APNS_TEAMID=
AUTO_ADD_TO_CART=
BROWSER_TRUSTED=
CAPTCHA_HANDLER_CAPTURE_TYPE=
CAPTCHA_HANDLER_POLL_INTERVAL=
CAPTCHA_HANDLER_RESPONSE_TIMEOUT=
CAPTCHA_HANDLER_SERVICE=
CAPTCHA_HANDLER_TOKEN=
CAPTCHA_HANDLER_USER_ID=
DESKTOP_NOTIFICATIONS=
DISCORD_NOTIFY_GROUP=
DISCORD_NOTIFY_GROUP_3060=
DISCORD_NOTIFY_GROUP_3060TI=
DISCORD_NOTIFY_GROUP_3070=
DISCORD_NOTIFY_GROUP_3070TI=
DISCORD_NOTIFY_GROUP_3080=
DISCORD_NOTIFY_GROUP_3080TI=
DISCORD_NOTIFY_GROUP_3090=
DISCORD_NOTIFY_GROUP_CORSAIR_SF=
DISCORD_NOTIFY_GROUP_RX6800=
DISCORD_NOTIFY_GROUP_RX6800XT=
DISCORD_NOTIFY_GROUP_RX6900XT=
DISCORD_NOTIFY_GROUP_RYZEN5600=
DISCORD_NOTIFY_GROUP_RYZEN5800=
DISCORD_NOTIFY_GROUP_RYZEN5900=
DISCORD_NOTIFY_GROUP_RYZEN5950=
DISCORD_NOTIFY_GROUP_SONYPS5C=
DISCORD_NOTIFY_GROUP_SONYPS5DE=
DISCORD_NOTIFY_GROUP_XBOXSX=
DISCORD_NOTIFY_GROUP_XBOXSS=
DISCORD_NOTIFY_GROUP_TEST=
DISCORD_WEB_HOOK=
EMAIL_PASSWORD=
EMAIL_TO=
EMAIL_USERNAME=
GOTIFY_PRIORITY=
GOTIFY_TOKEN=
GOTIFY_URL=
HEADLESS=
IN_STOCK_WAIT_TIME=
INCOGNITO=
LOG_LEVEL=
LOW_BANDWIDTH=
MAX_PRICE_SERIES_3060TI=800
MAX_PRICE_SERIES_3060=
MAX_PRICE_SERIES_3070=
MAX_PRICE_SERIES_3080=1200
MAX_PRICE_SERIES_3090=2200
MAX_PRICE_SERIES_3080TI=
MAX_PRICE_SERIES_3090=
MAX_PRICE_SERIES_CORSAIR_SF=
MAX_PRICE_SERIES_RX6800=
MAX_PRICE_SERIES_RX5700=
MAX_PRICE_SERIES_RX5700XT=800
MAX_PRICE_SERIES_RX6800XT=1100
MAX_PRICE_SERIES_RX6900XT=1700
MAX_PRICE_SERIES_RYZEN5600=
MAX_PRICE_SERIES_RYZEN5800=
MAX_PRICE_SERIES_RYZEN5900=
MAX_PRICE_SERIES_RYZEN5950=
MAX_PRICE_SERIES_SONYPS5C=800
MAX_PRICE_SERIES_SONYPS5DE=
MAX_PRICE_SERIES_XBOXSS=
MAX_PRICE_SERIES_XBOXSX=800
MAX_PRICE_SERIES_TEST=
MICROCENTER_LOCATION=
MQTT_BROKER_ADDRESS=
MQTT_BROKER_PORT=
MQTT_CLIENT_ID=
MQTT_PASSWORD=
MQTT_QOS=
MQTT_TOPIC=
MQTT_USERNAME=
OPEN_BROWSER="NO"
PAGE_BACKOFF_MIN=
PAGE_BACKOFF_MAX=
PAGE_SLEEP_MIN=2000000
PAGE_SLEEP_MAX=3600000
PAGE_TIMEOUT=
PAGERDUTY_INTEGRATION_KEY=
PAGERDUTY_SEVERITY=
PHILIPS_HUE_API_KEY=
PHILIPS_HUE_CLOUD_ACCESS_TOKEN=
PHILIPS_HUE_CLOUD_CLIENT_ID=
PHILIPS_HUE_CLOUD_CLIENT_SECRET=
PHILIPS_HUE_CLOUD_REFRESH_TOKEN=
PHILIPS_HUE_LAN_BRIDGE_IP=
PHILIPS_HUE_LIGHT_COLOR=
PHILIPS_HUE_LIGHT_IDS=
PHILIPS_HUE_LIGHT_PATTERN=
PHONE_CARRIER=
PHONE_NUMBER=
PLAY_SOUND=
PROXY_ADDRESS=
PROXY_PROTOCOL=
PROXY_PORT=
PUSHBULLET=
PUSHOVER_EXPIRE=
PUSHOVER_DEVICE=
PUSHOVER_PRIORITY=
PUSHOVER_RETRY=
PUSHOVER_SOUND=
PUSHOVER_TOKEN=
PUSHOVER_USER=
SCREENSHOT="no"
SHOW_ONLY_BRANDS=
SHOW_ONLY_MODELS=
SHOW_ONLY_SERIES=sonyps5c,rx6800xt,rx6900xt,3080,3090,3060ti
SLACK_CHANNEL=
SLACK_TOKEN=
SMTP_ADDRESS="smtp-mail.outlook.com"
SMTP_PORT="587"
STORES=amazon-ca,amd-ca,bestbuy-ca,canadacomputers,ebgames,memoryexpress,newegg-ca,walmart-ca,vuugo
TELEGRAM_ACCESS_TOKEN=****
TELEGRAM_CHAT_ID=****
TWILIO_ACCOUNT_SID=
TWILIO_AUTH_TOKEN=
TWILIO_FROM_NUMBER=
TWILIO_TO_NUMBER=
TWITCH_ACCESS_TOKEN=
TWITCH_CHANNEL=
TWITCH_CLIENT_ID=
TWITCH_CLIENT_SECRET=
TWITCH_REFRESH_TOKEN=
TWITTER_ACCESS_TOKEN_KEY=
TWITTER_ACCESS_TOKEN_SECRET=
TWITTER_CONSUMER_KEY=
TWITTER_CONSUMER_SECRET=
TWITTER_TWEET_TAGS=
STREAMLABS_ACCESS_TOKEN=
STREAMLABS_TYPE=
STREAMLABS_IMAGE=
STREAMLABS_SOUND=
FREEMOBILE_ID=
FREEMOBILE_API_KEY=
WEB_PORT=
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Speedmod88** [comment]
no one can help me??
