### ISSUE TITLE
[Bug]: Raspberry Pi 3

### ISSUE THREAD

**Issue by DotHack88** [jef/streetmerchant#2883]
### Expected Behavior

Hello I followed the steps as the guide says but unfortunately without success.

![Schermata 2021-12-12 alle 15 51 39](https://user-images.githubusercontent.com/40268801/145717237-30f77e61-3e75-438a-b0fd-ecc51ba47be2.png)

### Current Behavior

I followed as reported here from the guide:

**Download Node.js 15
    Clone this project git clone https://github.com/jef/streetmerchant.git.
    To checkout a particular reference, use git checkout <ref name> after cloning.
    Navigate to this project by entering cd streetmerchant.
    Run npm install.
    Make a copy of dotenv-example and name it dotenv.
    Edit the dotenv file to your liking using a text editor (like vscode).

    Run npm run start to start.

At any point you want the program to stop, use Ctrl + C.**

But when I start the program it gives me this error

### What operating system are you seeing the problem on?

Linux

### Relevant log output

```shell
pi@raspberrypi:~/streetmerchant $ npm run start

> streetmerchant@3.5.0 prestart
> npm run compile


> streetmerchant@3.5.0 compile /home/pi/streetmerchant
> tsc


> streetmerchant@3.5.0 start
> node build/src/index.js

ＳＴＲＥＥＴＭＥＲＣＨＡＮＴ
3.5.0
[15:40:58] info :: ℹ selected series: 3060, 3060ti, 3070, 3070ti, 3080, 3080ti, 3090, rx6700xt, rx6800, rx6800xt, rx6900xt, ryzen5600, ryzen5800, ryzen5900, ryzen5950, sf, sonyps5c, sonyps5de, xboxss, xboxsx
[15:40:59] info :: ℹ selected stores: amazon, bestbuy
[15:41:18] error :: ✖ something bad happened, resetting streetmerchant in 5 seconds Failed to launch the browser process!
/home/pi/streetmerchant/node_modules/puppeteer/.local-chromium/linux-869685/chrome-linux/chrome: 1: Syntax error: "(" unexpected


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md
 {
  "stack": "Error: Failed to launch the browser process!\n/home/pi/streetmerchant/node_modules/puppeteer/.local-chromium/linux-869685/chrome-linux/chrome: 1: Syntax error: \"(\" unexpected\n\n\nTROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md\n\n    at onClose (/home/pi/streetmerchant/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:194:20)\n    at Interface.<anonymous> (/home/pi/streetmerchant/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:184:68)\n    at Interface.emit (node:events:402:35)\n    at Interface.close (node:internal/readline/interface:496:10)\n    at Socket.onend (node:internal/readline/interface:229:10)\n    at Socket.emit (node:events:402:35)\n    at endReadableNT (node:internal/streams/readable:1343:12)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)"
}
[15:41:24] error :: ✖ something bad happened, resetting streetmerchant in 5 seconds Failed to launch the browser process!
/home/pi/streetmerchant/node_modules/puppeteer/.local-chromium/linux-869685/chrome-linux/chrome: 1: Syntax error: "(" unexpected


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md
 {
  "stack": "Error: Failed to launch the browser process!\n/home/pi/streetmerchant/node_modules/puppeteer/.local-chromium/linux-869685/chrome-linux/chrome: 1: Syntax error: \"(\" unexpected\n\n\nTROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md\n\n    at onClose (/home/pi/streetmerchant/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:194:20)\n    at Interface.<anonymous> (/home/pi/streetmerchant/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:184:68)\n    at Interface.emit (node:events:402:35)\n    at Interface.close (node:internal/readline/interface:496:10)\n    at Socket.onend (node:internal/readline/interface:229:10)\n    at Socket.emit (node:events:402:35)\n    at endReadableNT (node:internal/streams/readable:1343:12)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)"
}
[15:41:30] error :: ✖ something bad happened, resetting streetmerchant in 5 seconds Failed to launch the browser process!
/home/pi/streetmerchant/node_modules/puppeteer/.local-chromium/linux-869685/chrome-linux/chrome: 1: Syntax error: "(" unexpected


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md
```

### Configuration

```shell
# ** All configuration variables are optional **
# Copy this file and name it as `dotenv` (without backticks)
# Read https://jef.buzz/streetmerchant/getting-started/#customization for help on customizing this file
########################################################################################################

ASCII_BANNER=
ASCII_COLOR=
APNS_AUTHKEY=
APNS_BUNDLEID=
APNS_DEVICETOKEN=
APNS_KEYID=
APNS_PRODUCTION=
APNS_TEAMID=
AUTO_ADD_TO_CART=
BROWSER_TRUSTED=
CAPTCHA_HANDLER_CAPTURE_TYPE=
CAPTCHA_HANDLER_POLL_INTERVAL=
CAPTCHA_HANDLER_RESPONSE_TIMEOUT=
CAPTCHA_HANDLER_SERVICE=
CAPTCHA_HANDLER_TOKEN=
CAPTCHA_HANDLER_USER_ID=
DESKTOP_NOTIFICATIONS=
DISCORD_NOTIFY_GROUP=
DISCORD_NOTIFY_GROUP_3060=
DISCORD_NOTIFY_GROUP_3060TI=
DISCORD_NOTIFY_GROUP_3070=
DISCORD_NOTIFY_GROUP_3070TI=
DISCORD_NOTIFY_GROUP_3080=
DISCORD_NOTIFY_GROUP_3080TI=
DISCORD_NOTIFY_GROUP_3090=
DISCORD_NOTIFY_GROUP_CORSAIR_SF=
DISCORD_NOTIFY_GROUP_RX6800=
DISCORD_NOTIFY_GROUP_RX6800XT=
DISCORD_NOTIFY_GROUP_RX6900XT=
DISCORD_NOTIFY_GROUP_RYZEN5600=
DISCORD_NOTIFY_GROUP_RYZEN5800=
DISCORD_NOTIFY_GROUP_RYZEN5900=
DISCORD_NOTIFY_GROUP_RYZEN5950=
DISCORD_NOTIFY_GROUP_SONYPS5C=
DISCORD_NOTIFY_GROUP_SONYPS5DE=
DISCORD_NOTIFY_GROUP_XBOXSX=
DISCORD_NOTIFY_GROUP_XBOXSS=
DISCORD_NOTIFY_GROUP_TEST=
DISCORD_WEB_HOOK=
EMAIL_PASSWORD=
EMAIL_TO=
EMAIL_USERNAME=
GOTIFY_PRIORITY=
GOTIFY_TOKEN=
GOTIFY_URL=
HEADLESS=
IN_STOCK_WAIT_TIME=
INCOGNITO=
LOG_LEVEL=
LOW_BANDWIDTH=
MAX_PRICE_SERIES_3060=
MAX_PRICE_SERIES_3060TI=
MAX_PRICE_SERIES_3070=
MAX_PRICE_SERIES_3070TI=
MAX_PRICE_SERIES_3080=
MAX_PRICE_SERIES_3080TI=
MAX_PRICE_SERIES_3090=
MAX_PRICE_SERIES_CORSAIR_SF=
MAX_PRICE_SERIES_RX6800=
MAX_PRICE_SERIES_RX6800XT=
MAX_PRICE_SERIES_RX6900XT=
MAX_PRICE_SERIES_RYZEN5600=
MAX_PRICE_SERIES_RYZEN5800=
MAX_PRICE_SERIES_RYZEN5900=
MAX_PRICE_SERIES_RYZEN5950=
MAX_PRICE_SERIES_SONYPS5C=
MAX_PRICE_SERIES_SONYPS5DE=
MAX_PRICE_SERIES_XBOXSS=
MAX_PRICE_SERIES_XBOXSX=
MAX_PRICE_SERIES_TEST=
MICROCENTER_LOCATION=
MQTT_BROKER_ADDRESS=
MQTT_BROKER_PORT=
MQTT_CLIENT_ID=
MQTT_PASSWORD=
MQTT_QOS=
MQTT_TOPIC=
MQTT_USERNAME=
OPEN_BROWSER="false"
PAGE_BACKOFF_MIN=
PAGE_BACKOFF_MAX=
PAGE_SLEEP_MIN=
PAGE_SLEEP_MAX=
PAGE_TIMEOUT=
PAGERDUTY_INTEGRATION_KEY=
PAGERDUTY_SEVERITY=
PHILIPS_HUE_API_KEY=
PHILIPS_HUE_CLOUD_ACCESS_TOKEN=
PHILIPS_HUE_CLOUD_CLIENT_ID=
PHILIPS_HUE_CLOUD_CLIENT_SECRET=
PHILIPS_HUE_CLOUD_REFRESH_TOKEN=
PHILIPS_HUE_LAN_BRIDGE_IP=
PHILIPS_HUE_LIGHT_COLOR=
PHILIPS_HUE_LIGHT_IDS=
PHILIPS_HUE_LIGHT_PATTERN=
PHONE_CARRIER=
PHONE_NUMBER=
PLAY_SOUND=
PROXY_ADDRESS=
PROXY_PROTOCOL=
PROXY_PORT=
PUSHBULLET=
PUSHOVER_EXPIRE=
PUSHOVER_DEVICE=
PUSHOVER_PRIORITY=
PUSHOVER_RETRY=
PUSHOVER_SOUND=
PUSHOVER_TOKEN=
PUSHOVER_USER=
RESTART_TIME=
SCREENSHOT=
SCREENSHOT_DIR=
SHOW_ONLY_BRANDS=
SHOW_ONLY_MODELS=
SHOW_ONLY_SERIES=
SLACK_CHANNEL=
SLACK_TOKEN=
SMTP_ADDRESS=
SMTP_PORT=
STORES=
TELEGRAM_ACCESS_TOKEN=
TELEGRAM_CHAT_ID=
TWILIO_ACCOUNT_SID=
TWILIO_AUTH_TOKEN=
TWILIO_FROM_NUMBER=
TWILIO_TO_NUMBER=
TWITCH_ACCESS_TOKEN=
TWITCH_CHANNEL=
TWITCH_CLIENT_ID=
TWITCH_CLIENT_SECRET=
TWITCH_REFRESH_TOKEN=
TWITTER_ACCESS_TOKEN_KEY=
TWITTER_ACCESS_TOKEN_SECRET=
TWITTER_CONSUMER_KEY=
TWITTER_CONSUMER_SECRET=
TWITTER_TWEET_TAGS=
STREAMLABS_ACCESS_TOKEN=
STREAMLABS_TYPE=
STREAMLABS_IMAGE=
STREAMLABS_SOUND=
STREAMLABS_DURATION=
FREEMOBILE_ID=
FREEMOBILE_API_KEY=
WEB_PORT=
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Snej-Corleone** [comment]
I have exactly the same issue, would be great if anyone would know what to do...

**Comment by KosrenDQ** [comment]
Solved the issue by doing the following steps:

1. Install chromium with `sudo apt install chromium -y`
2. Add this line to the dotenv `PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium`

This may also be a solution for #2902 

Found relating information in #434 and the in the troubleshooting section of the blog (https://www.jef.buzz/streetmerchant/help/troubleshoot/)

**Comment by Snej-Corleone** [comment]
> Solved the issue by doing the following steps:
> 
> 
> 
> 1. Install chromium with `sudo apt install chromium -y`
> 
> 2. Add this line to the dotenv `PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium`
> 
> 
> 
> This may also be a solution for #2902 
> 
> 
> 
> Found relating information in #434 and the in the troubleshooting section of the blog (https://www.jef.buzz/streetmerchant/help/troubleshoot/)

Thank you, it worked !!
