### ISSUE TITLE
[Bug]: All "page" settings in dotenv get ignored

### ISSUE THREAD

**Issue by Rakmarok** [jef/streetmerchant#2993]
### Expected Behavior

What I did expect to happen:

SM to follow the page settings (PAGE_BACKOFF_MIN=, PAGE_BACKOFF_MAX=, PAGE_SLEEP_MIN=, PAGE_SLEEP_MAX, PAGE_TIMEOUT) I set. 

### Current Behavior

The current behaviour:

SM doesn't follow the page settings (PAGE_BACKOFF_MIN=, PAGE_BACKOFF_MAX=, PAGE_SLEEP_MIN=, PAGE_SLEEP_MAX, PAGE_TIMEOUT) I set and completely disregards them. Searching the sites I set just a few seconds later again, causing CAPTCHAs and 403 (forbidden) errors. Here is an example:

![SM 403](https://user-images.githubusercontent.com/55949253/161853477-e61c1968-3081-4af0-800b-2c9549949612.png)

I even set the values in STORES=, but that doesn't work either.

### What operating system are you seeing the problem on?

Windows

### Relevant log output

```shell
C:\OneDrive\Desktop>cd C:\Users\Rick_\streetmerchant

C:\Users\Rick_\streetmerchant>npm start run

> streetmerchant@3.5.0 prestart
> npm run compile


> streetmerchant@3.5.0 compile C:\Users\Rick_\streetmerchant
> tsc


> streetmerchant@3.5.0 start
> node build/src/index.js "run"

ＳＴＲＥＥＴＭＥＲＣＨＡＮＴ
3.5.0
[23:31:25] info :: ℹ selected brands: sony
[23:31:26] info :: ℹ selected models: ps5 console
[23:31:26] info :: ℹ selected series: sonyps5c
[23:31:26] info :: ℹ selected stores: amazon-de, expert, mediamarkt, otto, saturn
[23:31:27] info :: ✔ sound player found: cmdmp3win.exe
[23:32:15] info :: ✖ [otto] [sony (sonyps5c)] ps5 console :: OUT OF STOCK
[23:32:18] info :: ✖ [amazon-de] [sony (sonyps5c)] ps5 console :: OUT OF STOCK
[23:32:19] info :: ✖ [otto] [sony (sonyps5c)] ps5 console :: OUT OF STOCK
[23:32:21] info :: ✖ [mediamarkt] [sony (sonyps5c)] ps5 console :: OUT OF STOCK
[23:32:23] warn :: ✖ [mediamarkt] [sony (sonyps5c)] ps5 console :: STATUS CODE ERROR 403
[23:32:25] info :: ✖ [saturn] [sony (sonyps5c)] ps5 console :: OUT OF STOCK
[23:32:30] warn :: ✖ [saturn] [sony (sonyps5c)] ps5 console :: STATUS CODE ERROR 403
[23:32:46] info :: ✖ [expert] [sony (sonyps5c)] ps5 console :: OUT OF STOCK
[23:33:01] info :: ✖ [mediamarkt] [sony (sonyps5c)] ps5 console :: OUT OF STOCK
[23:33:07] info :: ✖ [amazon-de] [sony (sonyps5c)] ps5 console :: OUT OF STOCK
[23:33:07] warn :: ✖ [mediamarkt] [sony (sonyps5c)] ps5 console :: STATUS CODE ERROR 403
[23:33:07] info :: ✖ [otto] [sony (sonyps5c)] ps5 console :: OUT OF STOCK
[23:33:10] info :: ✖ [saturn] [sony (sonyps5c)] ps5 console :: OUT OF STOCK
[23:33:11] info :: ✖ [otto] [sony (sonyps5c)] ps5 console :: OUT OF STOCK
[23:33:14] warn :: ✖ [saturn] [sony (sonyps5c)] ps5 console :: STATUS CODE ERROR 403
[23:33:42] warn :: ✖ [mediamarkt] [sony (sonyps5c)] ps5 console :: STATUS CODE ERROR 403
[23:33:48] warn :: ✖ [saturn] [sony (sonyps5c)] ps5 console :: STATUS CODE ERROR 403
[23:33:55] info :: ✖ [expert] [sony (sonyps5c)] ps5 console :: OUT OF STOCK
[23:34:02] info :: ✖ [amazon-de] [sony (sonyps5c)] ps5 console :: OUT OF STOCK
[23:34:05] info :: ✖ [otto] [sony (sonyps5c)] ps5 console :: OUT OF STOCK
[23:34:09] info :: ✖ [otto] [sony (sonyps5c)] ps5 console :: OUT OF STOCK
[23:34:49] warn :: ✖ [amazon-de] [sony (sonyps5c)] ps5 console :: CAPTCHA
[23:34:49] error :: ✖ couldn't send discord DM An invalid token was provided. {
  "stack": "Error [TOKEN_INVALID]: An invalid token was provided.\n    at WebSocketManager.connect (C:\\Users\\Rick_\\streetmerchant\\node_modules\\discord.js\\src\\client\\websocket\\WebSocketManager.js:123:26)\n    at Client.login (C:\\Users\\Rick_\\streetmerchant\\node_modules\\discord.js\\src\\client\\Client.js:245:21)\n    at getDiscordClientAsync (C:\\Users\\Rick_\\streetmerchant\\build\\src\\messaging\\discord.js:182:30)\n    at sendDMAsync (C:\\Users\\Rick_\\streetmerchant\\build\\src\\messaging\\discord.js:89:28)\n    at Object.sendDMAndGetResponseAsync (C:\\Users\\Rick_\\streetmerchant\\build\\src\\messaging\\discord.js:173:27)\n    at Object.getCaptchaInputAsync (C:\\Users\\Rick_\\streetmerchant\\build\\src\\messaging\\captcha.js:19:36)\n    at Object.handleCaptchaAsync (C:\\Users\\Rick_\\streetmerchant\\build\\src\\store\\captcha-handler.js:36:40)\n    at async isItemInStock (C:\\Users\\Rick_\\streetmerchant\\build\\src\\store\\lookup.js:341:23)\n    at async lookupIem (C:\\Users\\Rick_\\streetmerchant\\build\\src\\store\\lookup.js:254:9)\n    at async lookup (C:\\Users\\Rick_\\streetmerchant\\build\\src\\store\\lookup.js:210:26)"
}
[23:34:49] warn :: [amazon-de] captcha handler failed
[23:34:50] info :: ✖ [mediamarkt] [sony (sonyps5c)] ps5 console :: OUT OF STOCK
[23:34:52] info :: ✖ [expert] [sony (sonyps5c)] ps5 console :: OUT OF STOCK
[23:34:54] warn :: ✖ [saturn] [sony (sonyps5c)] ps5 console :: STATUS CODE ERROR 403
[23:34:55] warn :: ✖ [mediamarkt] [sony (sonyps5c)] ps5 console :: STATUS CODE ERROR 403
[23:34:56] info :: ✖ [otto] [sony (sonyps5c)] ps5 console :: OUT OF STOCK
[23:34:59] info :: ✖ [otto] [sony (sonyps5c)] ps5 console :: OUT OF STOCK
```

### Configuration

```shell
# ** All configuration variables are optional **
# Copy this file and name it as `dotenv` (without backticks)
# Read https://jef.buzz/streetmerchant/getting-started/#customization for help on customizing this file
########################################################################################################

ASCII_BANNER=
ASCII_COLOR=
APNS_AUTHKEY=
APNS_BUNDLEID=
APNS_DEVICETOKEN=
APNS_KEYID=
APNS_PRODUCTION=
APNS_TEAMID=
AUTO_ADD_TO_CART=true
BROWSER_TRUSTED=
CAPTCHA_HANDLER_CAPTURE_TYPE=image
CAPTCHA_HANDLER_POLL_INTERVAL=5
CAPTCHA_HANDLER_RESPONSE_TIMEOUT=300
CAPTCHA_HANDLER_SERVICE=discord
CAPTCHA_HANDLER_TOKEN=[replaced]
CAPTCHA_HANDLER_USER_ID=
DESKTOP_NOTIFICATIONS=true
DISCORD_NOTIFY_GROUP=
DISCORD_NOTIFY_GROUP_3060=
DISCORD_NOTIFY_GROUP_3060TI=
DISCORD_NOTIFY_GROUP_3070=
DISCORD_NOTIFY_GROUP_3070TI=
DISCORD_NOTIFY_GROUP_3080=
DISCORD_NOTIFY_GROUP_3080TI=
DISCORD_NOTIFY_GROUP_3090=
DISCORD_NOTIFY_GROUP_CORSAIR_SF=
DISCORD_NOTIFY_GROUP_RX6800=
DISCORD_NOTIFY_GROUP_RX6800XT=
DISCORD_NOTIFY_GROUP_RX6900XT=
DISCORD_NOTIFY_GROUP_RYZEN5600=
DISCORD_NOTIFY_GROUP_RYZEN5800=
DISCORD_NOTIFY_GROUP_RYZEN5900=
DISCORD_NOTIFY_GROUP_RYZEN5950=
DISCORD_NOTIFY_GROUP_SONYPS5C=[replaced]
DISCORD_NOTIFY_GROUP_SONYPS5DE=[replaced]
DISCORD_NOTIFY_GROUP_XBOXSX=
DISCORD_NOTIFY_GROUP_XBOXSS=
DISCORD_NOTIFY_GROUP_TEST=[replaced]
DISCORD_WEB_HOOK=
EMAIL_PASSWORD=
EMAIL_TO=
EMAIL_USERNAME=
GOTIFY_PRIORITY=
GOTIFY_TOKEN=
GOTIFY_URL=
HEADLESS=
IN_STOCK_WAIT_TIME=60
INCOGNITO=
LOG_LEVEL=
LOW_BANDWIDTH=
MAX_PRICE_SERIES_3060=
MAX_PRICE_SERIES_3060TI=
MAX_PRICE_SERIES_3070=
MAX_PRICE_SERIES_3070TI=
MAX_PRICE_SERIES_3080=
MAX_PRICE_SERIES_3080TI=
MAX_PRICE_SERIES_3090=
MAX_PRICE_SERIES_CORSAIR_SF=
MAX_PRICE_SERIES_RX6800=
MAX_PRICE_SERIES_RX6800XT=
MAX_PRICE_SERIES_RX6900XT=
MAX_PRICE_SERIES_RYZEN5600=
MAX_PRICE_SERIES_RYZEN5800=
MAX_PRICE_SERIES_RYZEN5900=
MAX_PRICE_SERIES_RYZEN5950=
MAX_PRICE_SERIES_SONYPS5C=600
MAX_PRICE_SERIES_SONYPS5DE=500
MAX_PRICE_SERIES_XBOXSS=
MAX_PRICE_SERIES_XBOXSX=
MAX_PRICE_SERIES_TEST=500
MICROCENTER_LOCATION=
MQTT_BROKER_ADDRESS=
MQTT_BROKER_PORT=
MQTT_CLIENT_ID=
MQTT_PASSWORD=
MQTT_QOS=
MQTT_TOPIC=
MQTT_USERNAME=
OPEN_BROWSER=true
PAGE_BACKOFF_MIN=30000
PAGE_BACKOFF_MAX=90000
PAGE_SLEEP_MIN=30000
PAGE_SLEEP_MAX=60000
PAGE_TIMEOUT=60000
PAGERDUTY_INTEGRATION_KEY=
PAGERDUTY_SEVERITY=
PHILIPS_HUE_API_KEY=
PHILIPS_HUE_CLOUD_ACCESS_TOKEN=
PHILIPS_HUE_CLOUD_CLIENT_ID=
PHILIPS_HUE_CLOUD_CLIENT_SECRET=
PHILIPS_HUE_CLOUD_REFRESH_TOKEN=
PHILIPS_HUE_LAN_BRIDGE_IP=
PHILIPS_HUE_LIGHT_COLOR=
PHILIPS_HUE_LIGHT_IDS=
PHILIPS_HUE_LIGHT_PATTERN=
PHONE_CARRIER=
PHONE_NUMBER=
PLAY_SOUND=C:\Users\Rick_\streetmerchant\sound.wav
PROXY_ADDRESS=
PROXY_PROTOCOL=
PROXY_PORT=
PUSHBULLET=
PUSHOVER_EXPIRE=
PUSHOVER_DEVICE=
PUSHOVER_PRIORITY=
PUSHOVER_RETRY=
PUSHOVER_SOUND=
PUSHOVER_TOKEN=
PUSHOVER_USER=
REDIS_URL=
RESTART_TIME=
SCREENSHOT=true
SCREENSHOT_DIR=
SHOW_ONLY_BRANDS=sony
SHOW_ONLY_MODELS=ps5 console
SHOW_ONLY_SERIES=sonyps5c
SLACK_CHANNEL=
SLACK_TOKEN=
SMTP_ADDRESS=
SMTP_PORT=
SOUND_PLAYER=cmdmp3win.exe
STORES=amazon-de:30000,expert:30000,mediamarkt:30000,otto:30000,saturn:30000
TELEGRAM_ACCESS_TOKEN=
TELEGRAM_CHAT_ID=
TWILIO_ACCOUNT_SID=
TWILIO_AUTH_TOKEN=
TWILIO_FROM_NUMBER=
TWILIO_TO_NUMBER=
TWITCH_ACCESS_TOKEN=
TWITCH_CHANNEL=
TWITCH_CLIENT_ID=
TWITCH_CLIENT_SECRET=
TWITCH_REFRESH_TOKEN=
TWITTER_ACCESS_TOKEN_KEY=
TWITTER_ACCESS_TOKEN_SECRET=
TWITTER_CONSUMER_KEY=
TWITTER_CONSUMER_SECRET=
TWITTER_TWEET_TAGS=
STREAMLABS_ACCESS_TOKEN=
STREAMLABS_TYPE=
STREAMLABS_IMAGE=
STREAMLABS_SOUND=
STREAMLABS_DURATION=
FREEMOBILE_ID=
FREEMOBILE_API_KEY=
WEB_PORT=
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Rakmarok** [comment]
It works as intended when only using one store:

![SM one store](https://user-images.githubusercontent.com/55949253/161864146-54c0ed26-9959-44e2-af52-92f386db1dde.png)

**Comment by Rakmarok** [comment]
My old install from March/April recognises the values and waits the appropriate times:

![SM old install times](https://user-images.githubusercontent.com/55949253/161864298-35b18a46-c12e-4dae-bf39-9002fd48d93a.png)

**Comment by jef** [comment]
is this still happening?
