### ISSUE TITLE
ERR_SOCKET_BAD_PORT and wrong selected series

### ISSUE THREAD

**Issue by RuzbehS** [jef/streetmerchant#849]
### Description

 Hey, configured my .env file, but when I run the program the following happens:
[19:41:49] info :: ℹ selected stores: alternate, amazon-de, amazon-uk, arlt, caseking, cyberport, galaxus, gamestop, mediamarkt, mindfactory, notebooksbilliger, playstation, proshop-de, saturn
[19:41:49] info :: ℹ selected brands: sony
[19:41:49] info :: ℹ selected models: ps5 console, ps5 digital
[19:41:49] info :: ℹ selected series: 3070, 3080, 3090, rx6800, rx6800xt, rx6900xt, ryzen5600, ryzen5800, ryzen5900, ryzen5950, sonyps5c, sonyps5de, xboxss, xboxsx
[19:41:50] error :: ✖ something bad happened, resetting streetmerchant in 5 seconds options.port should be >= 0 and < 65536. Received NaN. {
  "code": "ERR_SOCKET_BAD_PORT",
  "stack": "RangeError [ERR_SOCKET_BAD_PORT]: options.port should be >= 0 and < 65536. Received NaN.\n    at validatePort (internal/validators.js:211:11)\n    at Server.listen (net.js:1444:5)\n    at Object.startAPIServer (C:\\Users\\Donald\\streetmerchant\\build\\web\\index.js:139:16)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async main (C:\\Users\\Donald\\streetmerchant\\build\\index.js:61:5)\n    at async loopMain (C:\\Users\\Donald\\streetmerchant\\build\\index.js:82:9)"

And then it repeats infinitely. Two Issues:
1.) I only want to search for ps5 consoles, so I left the "SHOW_ONLY_SERIES=" empty, however when I run the program it still searches for different GPUs and CPUs? What to do.
2.) So the main error has something to do with my port settings I guess, but I don't know where to change it. What to do?

Thank you.

**Comment by jef** [comment]
`WEB_PORT=""` should be a number between 0-65536. Ideally greater than 100.
