### ISSUE TITLE
Problem when commiting

### ISSUE THREAD

**Issue by sirNugg3ts** [jef/streetmerchant#915]
I'm trying to add some portuguese stores to the project, but whenever I try to commit I get this problem

```0 verbose cli [
0 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
0 verbose cli   'C:\\Users\\diogo\\Documents\\streetmerchant\\node_modules\\npm\\bin\\npm-cli.js',
0 verbose cli   'run',
0 verbose cli   'all'
0 verbose cli ]
1 info using npm@7.0.12
2 info using node@v12.19.0
3 timing config:load:defaults Completed in 2ms
4 timing config:load:file:C:\Users\diogo\Documents\streetmerchant\node_modules\npm\npmrc Completed in 1ms
5 timing config:load:builtin Completed in 1ms
6 timing config:load:cli Completed in 1ms
7 timing config:load:env Completed in 1ms
8 timing config:load:file:C:\Users\diogo\Documents\streetmerchant\.npmrc Completed in 0ms
9 timing config:load:project Completed in 1ms
10 timing config:load:file:C:\Users\diogo\.npmrc Completed in 1ms
11 timing config:load:user Completed in 1ms
12 timing config:load:file:C:\Program Files\nodejs\etc\npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:cafile Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:setUserAgent Completed in 0ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 10ms
19 verbose npm-session ab7656240cf6f966
20 timing npm:load Completed in 20ms
21 timing command:run-script Completed in 28925ms
22 verbose stack Error: command failed
22 verbose stack     at ChildProcess.<anonymous> (C:\Users\diogo\Documents\streetmerchant\node_modules\npm\node_modules\@npmcli\promise-spawn\index.js:64:27)
22 verbose stack     at ChildProcess.emit (events.js:314:20)
22 verbose stack     at maybeClose (internal/child_process.js:1021:16)
22 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
23 verbose cwd C:\Users\diogo\Documents\streetmerchant
24 verbose Windows_NT 10.0.19041
25 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\diogo\\Documents\\streetmerchant\\node_modules\\npm\\bin\\npm-cli.js" "run" "all"
26 verbose node v12.19.0
27 verbose npm  v7.0.12
28 error code 1
29 error path C:\Users\diogo\Documents\streetmerchant
30 error command failed
31 error command C:\Windows\system32\cmd.exe /d /s /c npm run build && npm run lint
32 verbose exit 1
```

any help?

**Comment by jef** [comment]
Looks like it it doesn't have the dependencies. Can you run `npm install` and then try and commit?

**Comment by sirNugg3ts** [comment]
I'm getting the same, from what I saw npm run lint is giving me the issue.
If I do lint:fix it's fine after I think but it modifies all files, I don't think it's supposed to do that

**Comment by sirNugg3ts** [comment]
Problem was with CR chars since I'm cloning in Windows
