### ISSUE TITLE
Store = scan is flagging a HDMI Cable by Club 3D as in Stock every 30 seconds

### ISSUE THREAD

**Issue by magma82** [jef/streetmerchant#919]
### Description
Hi Jef,

For the last couple of hours, the "Store=Scan" is flagging a 3080)] club 3d cac1373 10k 120hz v21 performance 48gbs cable aluminum hood black :: as in stock every 30 seconds. I have had to disable this as I am unsure how to exclude this from continuing.

Also, Store=box,ccl,evga-eu are error 503 or 403 and not reporting correctly.

Top work on this code mate, really appreciate this program!

see below:

![image](https://user-images.githubusercontent.com/26635477/100157499-8ec84000-2ea2-11eb-91c2-b9574d731a26.png)

**Comment by magma82** [comment]
some more information as to where it is pulling this URL:

if you browse to any of the 3070 3080 3090 pages at the very bottom (urls are in store > Model > Scan.ts)

https://www.scan.co.uk/shop/computer-hardware/gpu-nvidia/nvidia-geforce-rtx-3080-graphics-cards


"related items" on the site is the HDMI cable at the bottom of the page. it seems to be detecting that as a "in stock" GPU

**Comment by devon-badman** [comment]
This is an issue with the link builder picking up on a related item at the bottom of the list.

I fixed this by amending the productsSelector in src/store/model/scan.ts to read
`productsSelector: 'div.productList ul.productColumns li.product',`

**Comment by Dimitah** [comment]
I did as suggested above and here's what error I get in 2 minutes of scrapping:

_C:\streetmerchant\node_modules\puppeteer\lib\cjs\puppeteer\common\assert.js:26
        throw new Error(message);
              ^

Error: Request Interception is not enabled!
    at Object.exports.assert (C:\streetmerchant\node_modules\puppeteer\lib\cjs\puppeteer\common\assert.js:26:15)
    at HTTPRequest.continue (C:\streetmerchant\node_modules\puppeteer\lib\cjs\puppeteer\common\HTTPRequest.js:216:21)
    at PuppeteerBlocker.onRequest (C:\streetmerchant\node_modules\@cliqz\adblocker-puppeteer\dist\cjs\adblocker.js:229:33)
    at BlockingContext.onRequest (C:\streetmerchant\node_modules\@cliqz\adblocker-puppeteer\dist\cjs\adblocker.js:64:47)
    at C:\streetmerchant\node_modules\puppeteer\lib\cjs\vendor\mitt\src\index.js:51:62
    at Array.map (<anonymous>)
    at Object.emit (C:\streetmerchant\node_modules\puppeteer\lib\cjs\vendor\mitt\src\index.js:51:43)
    at Page.emit (C:\streetmerchant\node_modules\puppeteer\lib\cjs\puppeteer\common\EventEmitter.js:72:22)
    at C:\streetmerchant\node_modules\puppeteer\lib\cjs\puppeteer\common\Page.js:143:100
    at C:\streetmerchant\node_modules\puppeteer\lib\cjs\vendor\mitt\src\index.js:51:62_

Any chances that's related to the change I've made?
