### ISSUE TITLE
Issue with start script

### ISSUE THREAD

**Issue by traghubans** [jef/streetmerchant#967]
Getting an issue when running npm start. Here's the full breakdown:

 Cannot destructure property `stat` of 'undefined' or 'null'.
 at Object.<anonymous> (C:\\streetmerchant\node_modules\npm\node_modules\@npmcli\node-gyp\lib\index.js:2:29)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\\streetmerchant\node_modules\npm\node_modules\@npmcli\run-script\lib\run-script-pkg.js:4:55)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
C:\streetmerchant\node_modules\npm\node_modules\@npmcli\config\lib\index.js:163
      throw new Error('call config.load() before reading values')

**Comment by Ali-Aftab** [comment]
I had a similar issue. I found that the version of node I was running on was an outdated version. Go to [Nodejs.org](nodejs.org) and install the latest version. Then "npm install" and "npm run start".
