### ISSUE TITLE
ERR_SOCKET_BAD_PORT

### ISSUE THREAD

**Issue by CohesivePiano** [jef/streetmerchant#969]
I am trying to run the program and I keep getting the ERR_SOCKET_BAD_PORT error. I am pretty new at learning how to do this stuff and I need help. Thanks. 

"stack": "RangeError [ERR_SOCKET_BAD_PORT]: options.port should be >= 0 and < 65536. Received NaN.\n    at validatePort (internal/validators.js:211:11)\n    at Server.listen (net.js:1444:5)\n    at Object.startAPIServer (C:\\Users\\comp\\streetmerchant\\build\\web\\index.js:139:16)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async main (C:\\Users\\comp\\streetmerchant\\build\\index.js:61:5)\n    at async Timeout.loopMain [as _onTimeout] (C:\\Users\\comp\\streetmerchant\\build\\index.js:82:9)"

**Comment by CohesivePiano** [comment]
It ended up working after deleting     WEB_PORT="disabled"    from the .env
